### ISSUE TITLE
Streamer status should not be saved in the database

### ISSUE THREAD

**Issue by nargov** [jgstr/podcaststream#7]
https://github.com/jgstr/podcaststream/blob/146d4c31f2fa1c45a4dfdbfef76eb6716c016c02/database/sql-scripts/create-table.sql#L3

As we've discussed, the database should only hold the location of the streaming server (fake).
The streaming server needs to have an endpoint that returns the server's status.

```
AppServer                         Database                     StreamingServer(Fake)
---------                         --------                     ---------------------
     |                               |                                     |
     |===== get-streamer-url =======>|                                     |
     |<========= response ===========|                                     |
     |                               |                                     |
     |===================== get-streaming-server-status ==================>|
     |<=============================== response ===========================|
     |                               |                                     |

```

**Comment by jgstr** [comment]
This is very helpful. Thanks for the chart. I will replace that "Broadcasting" data with the mock-broadcaster/steamer endpoint. It's taking me awhile to understand how to use Docker and get Node and the Database to connect, but I should have everything up and running by tomorrow or Thursday. Thanks again.

**Comment by nargov** [comment]
From what I've seen in the configuration files, you seem to be well on your way.

**Comment by jgstr** [comment]
server.js now gets the broadcast URL from the database and GETS and HTTP request.
