### ISSUE TITLE
Replace setTimeout with docker-composer MySQL status check

### ISSUE THREAD

**Issue by jgstr** [jgstr/podcaststream#8]
Docker Compose does not wait for MySQL to completely initialize before running node server. Thus, node server returns a 'connection refused error.'
[https://github.com/jgstr/podcaststream/blob/master/app/server.js#L24](url)

**Comment by nargov** [comment]
[This question](https://stackoverflow.com/questions/42567475/docker-compose-check-if-mysql-connection-is-ready/42757250) has the answer - docker compose has a health check feature that holds off running the server until the database is really up.

**Comment by nargov** [comment]
Better yet: https://docs.docker.com/compose/startup-order/

**Comment by jgstr** [comment]
Thanks @nargov Those links helped. I used a less-than-optimal approach (setTimeout functions), but from what I read, the Docker engineers recommend orchestrating delays from application logic (rather than container-orchestration logic).
